server:
  port: 8090
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.2.1.178:3306/lake?useUnicode:true&characterEncoding:utf-8
    username: root
    password: 1234
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test
  messages:
    basename: messages/message,messages/message_modulea,messages/message_moduleb
    encoding: UTF-8
    cache-seconds: 3600
mybatis:
  mapperLocations: classpath:mybatis/mapper/*.xml
shiro:
  configLocation: classpath:ehcache-shiro.xml
  filterLinkedMap:
    /logout/**: logout
    /login/**: anon
    /logon/**: anon
    /druid/**: anon
    /user/**: anon
    /goods/**: anon
    /**: authc
    /: authc
jedis:
  pool:
    host: 127.0.0.1
    port: 6379
    config:
      maxTotal: 100
      maxIdle: 10
      maxWaitMillis: 100000